### ISSUE TITLE
Add regular command names, change current shorthand versions to aliases

### ISSUE THREAD

**Issue by rourke750** [Civcraft/NameLayer#14] opened 2015-01-17 18:14 UTC
make it so commands are easier

**Comment by drjawa** [comment] 2015-01-17 19:35
I'll write up some simplify versions in a bit

**Comment by drjawa** [comment] 2015-06-23 14:57
Citadel has commands and then aliases that map to those commands.

/ctinfo -> /cti

Idea is to make commands somewhat memorable and make namelayer less of a monster.

**Comment by suirad** [comment] 2015-06-26 15:04
Assign to me plz

**Comment by ttk2** [comment] 2015-06-26 22:52
can't assign it to you for some reason, but its yours.

**Comment by suirad** [comment] 2015-06-30 16:42
Probably because im not a contributor. Pull was merged, please close.

**Comment by drjawa** [comment] 2015-06-30 16:57
Is this on civtest? Just need to do a brief test and then it should be settled.

**Comment by suirad** [comment] 2015-06-30 17:02
The pull was just merged like 5min, so unless jenkins already rebuilt the jar, and someone put it on civtest, then no its not on there yet. Feel free.

**Comment by drjawa** [comment] 2015-06-30 18:12
Put the latest namelayer master on and civchat barfed this:

2015-06-30 14:10:04 [ERROR] Error occurred while enabling CivChat2 v1.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: vg/civcraft/mc/namelayer/command/Command
        at vg.civcraft.mc.civchat2.CivChat2.onEnable(CivChat2.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.ClassNotFoundException: vg.civcraft.mc.namelayer.command.Command
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45-internal]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45-internal]
        ... 12 more

**Comment by drjawa** [comment] 2015-06-30 18:16
Also minor amendment, but would prefer if the human aliases were the default and the abbreviations the aliases, though would require some additional changes. 

Little point in all this if /help namelayer just shows a bunch of shorthand versions.

**Comment by suirad** [comment] 2015-06-30 18:17
You need to update your jar of civchat2

**Comment by drjawa** [comment] 2015-06-30 18:22
Hmm, latest version available in jenkins is 1.0.2, not 1.0.3.

**Comment by drjawa** [comment] 2015-06-30 18:22
Though this confuses me: 2015-06-30 14:21:10 [INFO] [CivChat2] Enabling CivChat2 v1.0.3

**Comment by suirad** [comment] 2015-06-30 18:26
Im pretty sure CivChat2-live is outdated and is only the current version being used. I think what you are wanting is Civchat2-master. Reading the build log, it looks like its failing due to an outdated mercury.

**Comment by drjawa** [comment] 2015-06-30 18:27
Ok so we need to get that sorted to sort this out.

**Comment by ttk2** [comment] 2015-06-30 22:51
jekins in general needs a bit of upkeep paging @WildWeazel  you have been summoned for more suffering.

**Closed** 2015-07-09 02:56 UTC
Labels: Civtest - Pending verification, enhancement, P3 - Nice to have

**Comment by WildWeazel** [comment] 2015-07-09 03:54
I was offline for a week, @rourke750 did you take care of this already?

**Comment by ttk2** [comment] 2015-07-09 11:37
this one maybe, but JukeAlert won't compile due to an issue with its mercury dependencies.
