### ISSUE TITLE
GroupManager.invalidateCache NPE

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#146] opened 2015-12-28 16:42 UTC
[11:42:24 ERROR]: Could not pass event AsyncPluginBroadcastMessageEvent to NameLayer v2.5.21
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d97e08b-880a532]
        at vg.civcraft.mc.mercury.events.BukkitEventManager.fireMessage(BukkitEventManager.java:11) [Mercury-1.1.108.jar:?]
        at vg.civcraft.mc.mercury.events.EventManager.fireMessage(EventManager.java:15) [Mercury-1.1.108.jar:?]
        at vg.civcraft.mc.mercury.rabbitmq.RabbitConsumer.handleDelivery(RabbitConsumer.java:83) [Mercury-1.1.108.jar:?]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144) [Mercury-1.1.108.jar:?]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99) [Mercury-1.1.108.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.GroupManager.invalidateCache(GroupManager.java:253) ~[?:?]
        at vg.civcraft.mc.namelayer.listeners.MercuryMessageListener.onMercuryMessage(MercuryMessageListener.java:37) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 11 more

**Comment by Maxopoly** [comment] 2015-12-31 00:06
This might be what's causing https://github.com/Civcraft/NameLayer/issues/150.

Let's just hope this was not caused by a deeper issue and a simple null check here will do the trick. Consider it fixed by https://github.com/Civcraft/NameLayer/commit/e7487d5839e00716af9658a596c29194fd84fa02

**Closed by Maxopoly** 2015-12-31 00:06 UTC
Labels: bug, P1 - Critical
