### ISSUE TITLE
Group permissions dont update properly

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/NameLayer#150] opened 2015-12-30 22:48 UTC
This was modmailed multiple times before and I was able to reproduce it. Basically sometimes if you remove people from groups or add them to groups their permissions wont update which means they are still (not) able to use factories/place on bastions etc.. It doesnt seem to be persistent though, when I tried it with different groups it worked for one and didnt for the other.

**Comment by rourke750** [comment] 2015-12-30 23:58
Do restarts fix it?

**Comment by Maxopoly** [comment] 2015-12-30 23:59
no

**Comment by Maxopoly** [comment] 2015-12-30 23:59
At least that's what I was told

**Comment by rourke750** [comment] 2015-12-31 00:00
What about removing or readding?  Actually for bastion I believe that the
member type they are on needs blockbreak perm I believe to use.

**Comment by Maxopoly** [comment] 2015-12-31 00:03
Removing didnt take the permission away, I was still able to place afterwards (no restart inbetween though). Removing and readding didnt work for the other issues, it happens for every added person for some groups and yeah Bastion just checks perms for the bastion block.

**Comment by rourke750** [comment] 2015-12-31 00:26
For the groups affected have they ever been merged into?

**Comment by Maxopoly** [comment] 2015-12-31 00:27
I'll ask

**Comment by Maxopoly** [comment] 2015-12-31 01:08
I just tested it with merging into the group and merging the bastiongroup itself, both work as intended.

**Comment by Maxopoly** [comment] 2016-01-04 22:31
This is still happening, but it seems to get fixed by the restart. The group this was occuring for had another group merged into it a while ago.

**Comment by Maxopoly** [comment] 2016-01-11 10:41
@rourke750 So people told me they can fix this for doors by breaking it and placing it again after the new person was added to the group. Sounds like an issue with block permission caching.

**Comment by rourke750** [comment] 2016-01-11 17:12
https://github.com/Civcraft/NameLayer/blob/master/NameLayerMain/src/vg/civcraft/mc/namelayer/GroupManager.java#L143

Something is wrong with this logic then.  I'm focusing on bettershards knocking out the issues.
@erocs @Maxopoly @ProgrammerDan If you just want to glance over that and see if anything sticks out.

**Comment by erocs** [comment] 2016-01-11 17:52
Does breaking and replacing the door fix all the blocks for that person or
just the door? Also the daily restart does fix this?

**Comment by Maxopoly** [comment] 2016-01-11 18:57
Just the single door. I think the restart fixes it, yeah (it does for bastions at least).

**Comment by ProgrammerDan** [comment] 2016-01-12 14:46
gonna have to look at that line a bit closer, first pass it looks ... okayish ... but how you're handling the multi-indexing is a little concerning.

Effectively, you get the group from DAO, but if you have a cached version by name, you throw away the version you just got fresh from the DB via the DAO and use the cached version from the named list.

That's probably not good. If you've bothered to query the database, unless for some reason you suspect the database doesn't have the most recent information, you should prefer the information from the db. 

Anyway, might be misunderstanding.

**Comment by jjj5311** [comment] 2016-01-12 15:42
IIRC updating players in groups or their group permissions updates the database and does nothing with the cache. 

Should the cache be invalidated anytime there is a change to the group? so it has to pull from the database? removemember/promoteplayer/update premissions?

**Comment by ProgrammerDan** [comment] 2016-01-12 15:55
check the pull for what I mean. View diff for illustration...

**Comment by jjj5311** [comment] 2016-01-12 16:00
I have not been doing much development of anything lately so I may be misunderstanding but if the group is in the cache won't it be returned before entering the else statement to check db?

https://github.com/Civcraft/NameLayer/pull/153/files#diff-c69a82c6840d6af9abc1feda6fc3086fR145

**Comment by ProgrammerDan** [comment] 2016-01-12 16:03
There are two cache lists now -- one by ID and one by name. If the group is in the ID cache you're right, but if for some reason it isn't in the cache but was in the byName cache, then the inconsistency appears.

**Comment by jjj5311** [comment] 2016-01-12 16:24
huh. I understand what your pull is doing for inconsisitency... but isn't the problem that the cached Group object is out of date?

EXAMPLE
groupid = 123 and name = group1
player_x adds player_y to group1
player_y tries to break a block or any action
getGroup(id) or getGroup(name) returns the cached Group with player_y not in the group
player_y cannot do the action

**Comment by ProgrammerDan** [comment] 2016-01-12 16:28
My theory is this:

group doesn't exist in idCache (dunno why) but does exist in nameCache. 

Player_x adds player_y to group1 -- this is written to DB, neither cache is updated(!! -- need to check write logic, next up on my list)

player_y tries to break a block/action

code uses getGroup(id) but doesn't exist in idCache. The old version existed in nameCache, so the prior code would have returned the old version AND populated the idCache with the old version, so all future calls would use the old group (which lacks player_y).

See the problem?

**Comment by jjj5311** [comment] 2016-01-12 16:34
yep totally agree with you and i think we are in agreement that when
player_x modifies the groupis where the problem is the cache (both caches i
guess) should be invalidated for that group so next time it is pulled fresh
from the db

**Comment by ProgrammerDan** [comment] 2016-01-12 16:35
Right on :)

**Comment by rourke750** [comment] 2016-01-12 17:15
I'm just going to change the api so each group object stores all the ids.

**Comment by ProgrammerDan** [comment] 2016-03-18 20:58
This is resolved: see latest https://github.com/Civcraft/NameLayer/blob/master/NameLayerMain/src/vg/civcraft/mc/namelayer/GroupManager.java#L235

Does not exhibit this poorly behaved caching. Closing for now, can reopen if new reports surface.

**Closed by ProgrammerDan** 2016-03-18 20:58 UTC
Labels: bug, P1 - Critical
