### ISSUE TITLE
/nllp NPE in GroupPermission.listPermsforPlayerType

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#131] opened 2015-09-14 02:50 UTC
2010-01-01 01:01:01 [INFO] ABC issued server command: /nllp XYZ MEMBERS
2010-01-01 01:01:01 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'nllp' in plugin NameLayer v2.4.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.permission.GroupPermission.listPermsforPlayerType(GroupPermission.java:79) ~[?:?]
        at vg.civcraft.mc.namelayer.command.commands.ListPermissions.execute(ListPermissions.java:59) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:87) ~[?:?]
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:70) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 15 more

**Comment by suirad** [comment] 2015-10-05 21:40
This is kinda tricky. I think this would fix it, but i am not sure if the [pType.name()](https://github.com/Civcraft/NameLayer/blob/master/src/vg/civcraft/mc/namelayer/permission/GroupPermission.java#L79) is what is causing the npe or if [perms.get(type)](https://github.com/Civcraft/NameLayer/blob/master/src/vg/civcraft/mc/namelayer/permission/GroupPermission.java#L78) is returning a null.

[i have an attempted fix here](https://gist.github.com/suirad/a1dc0c9cc525333dabf0), please review.

**Comment by Maxopoly** [comment] 2015-10-13 15:35
The NPE has to be caused by perms.get(type) returning null, because name() on an enum simply gives the name, I dont think an NPE can occur there unless the instance it is run on is null.

Fixed by https://github.com/Civcraft/NameLayer/commit/90708e28073f41d386b32fd82da4101a215d5766

**Closed by Maxopoly** 2015-10-13 15:35 UTC
Labels: bug, P2 - Needed
