### ISSUE TITLE
Group shows itself twice in listing, player tries to merge them which deletes it

### ISSUE THREAD

**Issue by drjawa** [Civcraft/NameLayer#83] opened 2015-03-08 22:25 UTC

**Comment by rourke750** [comment] 2015-03-08 22:26
wut.

**Comment by drjawa** [comment] 2015-03-08 22:41
Yeah, figuring this one out might be tricky.

**Comment by rourke750** [comment] 2015-03-08 22:42
I think we should just ignore it.

**Comment by drjawa** [comment] 2015-03-08 22:43
Well, the player has lost access to all their reinforcements.

**Comment by rourke750** [comment] 2015-03-08 23:05
Can you tp to an area where there were his reinforcements were and see what
group they are on.  Worst comes to worse we need to load a backup and find
what the group id was and manually fix it.

**Comment by drjawa** [comment] 2015-03-08 23:11
I'll ask and report back

Excerpts from rourke750's message of 2015-03-08 16:05:28 -0700:
> Can you tp to an area where there were his reinforcements were and see what
> group they are on.  Worst comes to worse we need to load a backup and find
> what the group id was and manually fix it.

**Comment by ttk2** [comment] 2015-03-09 02:50
could this be related 2015-03-08 22:54:04 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '33dea67f-bd63-4ae4-9dcc-3fa41d-c695aa-66755' for key 'uq_meber_faction'

**Comment by rourke750** [comment] 2015-03-09 12:40
They most likely fucked up their group.  Can you load up a back up and ask what the group was called.  We need to find what the group id was and manually create a new group and then through mysql set the group id to the new group we created.  After that transfer the group to the player and problem solved.

**Comment by ttk2** [comment] 2015-03-09 20:11
list steps please? Also how do I dig stuff out of a sqldump?

**Comment by rourke750** [comment] 2015-03-09 22:39
I'll prob just do this with erocs so if you want to just download a backup or something for him i can have him do it all.

**Comment by ttk2** [comment] 2015-03-10 15:15
he should just be able to gab the latest sqldump trivially we need to
figure out how old of a backup we need to restore.

**Comment by rourke750** [comment] 2015-03-10 15:40
The day before he merged should work. Its just needed to find a single
field.

**Comment by rourke750** [comment] 2015-03-11 11:28
@drjawa I'm still waiting on info any luck on this?

**Comment by ttk2** [comment] 2015-03-12 16:16
this is fixed now, I have the sqldump backup, what do I need to do with it?

**Comment by ttk2** [comment] 2015-03-12 16:16
I mean the problem is fixed now but we still have cleanup.

**Comment by rourke750** [comment] 2015-03-12 17:17
Did you get the information from the player?

**Comment by ttk2** [comment] 2015-03-13 04:54
what do we need from them?

**Comment by rourke750** [comment] 2015-03-13 14:57
https://github.com/Civcraft/NameLayer/issues/83#issuecomment-77845946

**Comment by rourke750** [comment] 2015-04-03 21:23
https://github.com/Civcraft/NameLayer/commit/6c567fe81a7ee42e5299a7d37f1fc9732b887e6c

**Closed by rourke750** 2015-04-03 21:23 UTC
Labels: bug, P2 - Needed
